---
title: "the link between stress and depression and the 10 simple words that could help"
author:
  - name: nguetse nanjou astryde vanessa
date: 10-21-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


![]https://www.theguardian.com/society/2019/oct/13/the-link-between-stress-and-depression-and-the-10-simple-words-that-could-help#img-1


## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| stress cycle        | stress follows a cycle event which circle around each step increasing the severity of the next step                   |
| mental model        | explanation of someone's thought process about how something works, in the real world.         |

## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Dean Burnett, neuroscientist                        |
| Published in?                | 13-10-2019                                                       |
| General topic?               |Stress may once just have been a kind of executive trophy – “I’m so stressed!” – but recent research suggests it is a key element in developing mental health problems such as depression and anxiety.                      |
| Procedure/what was examined? |  stress is also very stimulating. It releases several potent chemicals into your bloodstream cortisol for instance, which amps up your heart rate, muscle tension, glucose uptake, even your immune system responses.The trigger, the activation of the stress response, comes from our brains, with the hypothalamic pituitary adrenal (HPA) a complex association between the hypothalamus and the pituitary and adrenal glands  as the key element. The HPA is basically the link between the brain and the body when it comes to stress. When our brain decides that stress is required, signals are sent to the HPA axis, which in turn releases a complex sequence of chemicals that ends up with stress hormones, such as cortisol and glucocorticoids, being released into our bloodstream.But here’s the problem. In many people, this ability of the HPA axis to recognise when there’s enough stress chemical in the body and so cease production is disrupted in some way. The HPA axis can start the physical stress response but doesn’t seem to know when to stop.This might sound like a mild annoyance but there’s mounting evidence to suggest that it’s a cause of multiple mental health problems, particularly depression. |
| Conclusions/discovery?       |  There is no easy fix. But at the very start of the session, we are given a brief, basic set of instructions that could, if adhered to, tangibly reduce stress. There were just 10 words: “Face your fears. Be more active. Watch what you drink.”      |
| Remaining questions?         | why this ten words is so difficult to respect |


<https://www.the guardian.com/.../the-link-betwenn-stress-and-depression-and-the-10-simple-words-that-could-help>



