---
title: "type 2 diabete:causes and preventions"
author:
  - name: nguetse nanjou astryde vanessa
date: 11-25-2019
output:
  distill::distill_article:
    self_contained: false
---


## Article analysis n°2

# Low-carb diet may reduce diabetes risk independent of weight loss

## Name of magazine + source

 sciencedaily([url](www.sciencedaily.com/releases/2019/06/190620100036.htm))

## Vocabulary

| Words from the text  | Synonym / explanation in   English |
| -------------------- | ---------------------------------- |
| stroke               |disease that affects the arteries leading to and within the brain. |
| obviously            |clearly, evidently    |


## Analysis table

| Researchers                  | arker N. Hyde, Teryn N. Sapper                      |
| ---------------------------- | ------------------------------------------------------------------- |
| Published   in?              | June 20, 2019                                                     |
| General topic?               |A low-carb diet may have benefits for people at risk of developing type 2 diabetes even if they don't lose any weight.                   |
| Procedure/what was examined? | Over about four months, each study participant ate three month-long controlled diets -- high-carb, moderate-carb and low-carb -- with a two-week break between diets. The order in which the participants ate the diets was randomly assigned.The research team, led by research scientist Parker Hyde, ensured that the participants would not lose weight by providing them with pre-prepared meals that contained an amount of calories equal to their energy expenditure.After eating the low-carb diet, the participants had a variety of significantly improved health measures, particularly lower triglycerides and improved cholesterol readings.

| Conclusions/discovery?       | Despite the fact that the low-carb diet contained 2.5 times more saturated fat than the high-carb diet, it decreased saturated fat in the bloodstream and was associated with an increase in the size of cholesterol particles in the blood, which decreases the risk of desease and increased fat-burning efficiency after a low-carb diet and an improvement in blood sugar     |
| Remaining questions?         |adopted a low carbohydrate diet would it be an effective solution against diabetes? |



