---
title: "type 2 diabete:causes and prevention"
description: |
  A short description of the post.
author:
  - name: nguetse nanjou astryde vanessa
date: 11-28-2019
output:
  distill::distill_article:
    self_contained: false
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Article analysis n_3

# Vitamin D supplementation may slow diabetes progression

# Name of the magazine + source
sciensedaily([url](www.sciencedaily.com/releases/2019/07/190725211631.htm))
---
## Vocabulary

| words from the text | synonym/explanation in english                             |
| ------------------- | ---------------------------------------------------------- |
| Huge burden         | something that is carried with the great importance or seriousness                                    |


    
## Analysis table   

| Researchers                  | Patricia Lemieux, John S Weisnagel and Annabelle Z Caro                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| ---------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|  Published in in?            | July 25, 2019                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| General topic?               | The study findings suggest that high-dose supplementation of vitamin D can improve glucose metabolism to help prevent the development and progression of diabetes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Procedure/what was examined? | In this study, researchers, examined the effect of vitamin D supplementation on glucose metabolism in patients newly diagnosed with type 2 diabetes or identified as at high risk of developing the condition. Markers of insulin function and glucose metabolism were measured before and after six months of high-dose vitamin D supplementation (approximately 5-10 times the recommended dose). Although only 46% of study participants were determined to have low vitamin D levels at the start of the study, supplementation with vitamin D significantly improved the action of insulin in muscle tissue of participants after six months.  |
|  Conclusions/discovery       | The reason we saw improvements in glucose metabolism following vitamin D supplementation in those at high risk of diabetes, or with newly diagnosed diabetes, while other studies failed to demonstrate an effect in people with long-standing type 2 diabetes is unclear. This could be due to the fact that improvements in metabolic function are harder to detect in those with longer-term disease or that a longer treatment time is needed to see the benefits.                                                                                                                                                                              |
|  Remaining question?         | would vitD supplementation be influenced by genetic or clinical factors?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.
